### ISSUE TITLE
Trends for individual symptoms

### ISSUE THREAD

**Issue by klpn** [csss-resultat/openData#1]
It would be useful to have trends for individual symptoms, as shown on the Symtom tab in the dashboard, available as data here. These cannot be downloaded as CSV from the dashboard either, as far as I can see.

**Comment by csss-resultat** [comment]
Hey, thanks for you comment and interest in our data. I will make sure to make this data also available here in the coming days.

**Comment by klpn** [comment]
I see it is available now, so maybe I can close the issue. Thanks!
